//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-06-14 15:43:58 by 群升科技
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace EMS.Model 
{
    /// <summary>
    /// 数据表实体类：T_TestEntity 
    /// </summary>
    [Serializable()]
    public class T_TestEntity
    {    
		            
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Name { get; set; }

                    
		/// <summary>
		/// varchar:
		/// </summary>	
                 
		public string Remark { get; set; }

                    
		/// <summary>
		/// nchar:
		/// </summary>	
                 
		public string aaa { get; set; }

           
    }    
}
	